apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: assignment-backend-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: assignment-backend
      release: assignment-backend
  namespaceSelector:
    matchNames:
      - app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
